//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace UI
{
	public class UIAttachment<T> : BaseAttachment<T> {
	}

	public class UIAttachment : BaseAttachment{
		public GameObject m_collisionTrigger;

		public bool willCollide = true;

		public override void Update(){
			if(willCollide && !m_collisionTrigger.activeSelf)
				m_collisionTrigger.SetActive(true);
			else if(!willCollide && m_collisionTrigger.activeSelf)
				m_collisionTrigger.SetActive(false);
		}
	}
}

