//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace UI
{
	public class UIAttachment<T> : BaseAttachment<T> {
	}

	public class UIAttachment : BaseAttachment{
		protected GameObject m_collisionTriggers;

		public bool willCollide = true;

		public override void Awake(){
			for(int i =0; i < transform.childCount; i++){
				if(transform.GetChild(i).name == "BoxAreaTrigger"){
					m_collisionTriggers = transform.GetChild(i).gameObject;
				}
			}

			base.Awake();
		}

		public override void Update(){
			if(willCollide && !m_collisionTriggers.activeSelf)
				m_collisionTriggers.SetActive(true);
			else if(!willCollide && m_collisionTriggers.activeSelf)
				m_collisionTriggers.SetActive(false);
		}
	}
}

